// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by figma_tokens_builder

// ignore_for_file: library_private_types_in_public_api, camel_case_types

import 'dart:ui';
import 'package:flutter/material.dart';

class FigmaQ8Color extends ThemeExtension<FigmaQ8Color> {
  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color primaryFixed;
  final Color onPrimaryFixed;
  final Color primaryFixedDim;
  final Color onPrimaryFixedVariant;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color secondaryFixed;
  final Color onSecondaryFixed;
  final Color secondaryFixedDim;
  final Color onSecondaryFixedVariant;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color tertiaryFixed;
  final Color onTertiaryFixed;
  final Color tertiaryFixedDim;
  final Color onTertiaryFixedVariant;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color outline;
  final Color background;
  final Color onBackground;
  final Color surface;
  final Color onSurface;
  final Color surfaceVariant;
  final Color onSurfaceVariant;
  final Color inverseSurface;
  final Color inverseOnSurface;
  final Color inversePrimary;
  final Color shadow;
  final Color surfaceTint;
  final Color outlineVariant;
  final Color scrim;
  final Color surfaceContainerHighest;
  final Color surfaceContainerHigh;
  final Color surfaceContainer;
  final Color surfaceContainerLow;
  final Color surfaceContainerLowest;
  final Color surfaceBright;
  final Color surfaceDim;

  const FigmaQ8Color({
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.primaryFixed,
    required this.onPrimaryFixed,
    required this.primaryFixedDim,
    required this.onPrimaryFixedVariant,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.secondaryFixed,
    required this.onSecondaryFixed,
    required this.secondaryFixedDim,
    required this.onSecondaryFixedVariant,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.tertiaryFixed,
    required this.onTertiaryFixed,
    required this.tertiaryFixedDim,
    required this.onTertiaryFixedVariant,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.outline,
    required this.background,
    required this.onBackground,
    required this.surface,
    required this.onSurface,
    required this.surfaceVariant,
    required this.onSurfaceVariant,
    required this.inverseSurface,
    required this.inverseOnSurface,
    required this.inversePrimary,
    required this.shadow,
    required this.surfaceTint,
    required this.outlineVariant,
    required this.scrim,
    required this.surfaceContainerHighest,
    required this.surfaceContainerHigh,
    required this.surfaceContainer,
    required this.surfaceContainerLow,
    required this.surfaceContainerLowest,
    required this.surfaceBright,
    required this.surfaceDim,
  });

  static const dark = FigmaQ8Color(
    primary: FigmaQ8Tokens.primaryDark,
    onPrimary: FigmaQ8Tokens.onPrimaryDark,
    primaryContainer: FigmaQ8Tokens.primaryContainerDark,
    onPrimaryContainer: FigmaQ8Tokens.onPrimaryContainerDark,
    primaryFixed: FigmaQ8Tokens.primaryFixedDark,
    onPrimaryFixed: FigmaQ8Tokens.onPrimaryFixedDark,
    primaryFixedDim: FigmaQ8Tokens.primaryFixedDimDark,
    onPrimaryFixedVariant: FigmaQ8Tokens.onPrimaryFixedVariantDark,
    secondary: FigmaQ8Tokens.secondaryDark,
    onSecondary: FigmaQ8Tokens.onSecondaryDark,
    secondaryContainer: FigmaQ8Tokens.secondaryContainerDark,
    onSecondaryContainer: FigmaQ8Tokens.onSecondaryContainerDark,
    secondaryFixed: FigmaQ8Tokens.secondaryFixedDark,
    onSecondaryFixed: FigmaQ8Tokens.onSecondaryFixedDark,
    secondaryFixedDim: FigmaQ8Tokens.secondaryFixedDimDark,
    onSecondaryFixedVariant: FigmaQ8Tokens.onSecondaryFixedVariantDark,
    tertiary: FigmaQ8Tokens.tertiaryDark,
    onTertiary: FigmaQ8Tokens.onTertiaryDark,
    tertiaryContainer: FigmaQ8Tokens.tertiaryContainerDark,
    onTertiaryContainer: FigmaQ8Tokens.onTertiaryContainerDark,
    tertiaryFixed: FigmaQ8Tokens.tertiaryFixedDark,
    onTertiaryFixed: FigmaQ8Tokens.onTertiaryFixedDark,
    tertiaryFixedDim: FigmaQ8Tokens.tertiaryFixedDimDark,
    onTertiaryFixedVariant: FigmaQ8Tokens.onTertiaryFixedVariantDark,
    error: FigmaQ8Tokens.errorDark,
    onError: FigmaQ8Tokens.onErrorDark,
    errorContainer: FigmaQ8Tokens.errorContainerDark,
    onErrorContainer: FigmaQ8Tokens.onErrorContainerDark,
    outline: FigmaQ8Tokens.outlineDark,
    background: FigmaQ8Tokens.backgroundDark,
    onBackground: FigmaQ8Tokens.onBackgroundDark,
    surface: FigmaQ8Tokens.surfaceDark,
    onSurface: FigmaQ8Tokens.onSurfaceDark,
    surfaceVariant: FigmaQ8Tokens.surfaceVariantDark,
    onSurfaceVariant: FigmaQ8Tokens.onSurfaceVariantDark,
    inverseSurface: FigmaQ8Tokens.inverseSurfaceDark,
    inverseOnSurface: FigmaQ8Tokens.inverseOnSurfaceDark,
    inversePrimary: FigmaQ8Tokens.inversePrimaryDark,
    shadow: FigmaQ8Tokens.shadowDark,
    surfaceTint: FigmaQ8Tokens.surfaceTintDark,
    outlineVariant: FigmaQ8Tokens.outlineVariantDark,
    scrim: FigmaQ8Tokens.scrimDark,
    surfaceContainerHighest: FigmaQ8Tokens.surfaceContainerHighestDark,
    surfaceContainerHigh: FigmaQ8Tokens.surfaceContainerHighDark,
    surfaceContainer: FigmaQ8Tokens.surfaceContainerDark,
    surfaceContainerLow: FigmaQ8Tokens.surfaceContainerLowDark,
    surfaceContainerLowest: FigmaQ8Tokens.surfaceContainerLowestDark,
    surfaceBright: FigmaQ8Tokens.surfaceBrightDark,
    surfaceDim: FigmaQ8Tokens.surfaceDimDark,
  );

  static const light = FigmaQ8Color(
    primary: FigmaQ8Tokens.primaryLight,
    onPrimary: FigmaQ8Tokens.onPrimaryLight,
    primaryContainer: FigmaQ8Tokens.primaryContainerLight,
    onPrimaryContainer: FigmaQ8Tokens.onPrimaryContainerLight,
    primaryFixed: FigmaQ8Tokens.primaryFixedLight,
    onPrimaryFixed: FigmaQ8Tokens.onPrimaryFixedLight,
    primaryFixedDim: FigmaQ8Tokens.primaryFixedDimLight,
    onPrimaryFixedVariant: FigmaQ8Tokens.onPrimaryFixedVariantLight,
    secondary: FigmaQ8Tokens.secondaryLight,
    onSecondary: FigmaQ8Tokens.onSecondaryLight,
    secondaryContainer: FigmaQ8Tokens.secondaryContainerLight,
    onSecondaryContainer: FigmaQ8Tokens.onSecondaryContainerLight,
    secondaryFixed: FigmaQ8Tokens.secondaryFixedLight,
    onSecondaryFixed: FigmaQ8Tokens.onSecondaryFixedLight,
    secondaryFixedDim: FigmaQ8Tokens.secondaryFixedDimLight,
    onSecondaryFixedVariant: FigmaQ8Tokens.onSecondaryFixedVariantLight,
    tertiary: FigmaQ8Tokens.tertiaryLight,
    onTertiary: FigmaQ8Tokens.onTertiaryLight,
    tertiaryContainer: FigmaQ8Tokens.tertiaryContainerLight,
    onTertiaryContainer: FigmaQ8Tokens.onTertiaryContainerLight,
    tertiaryFixed: FigmaQ8Tokens.tertiaryFixedLight,
    onTertiaryFixed: FigmaQ8Tokens.onTertiaryFixedLight,
    tertiaryFixedDim: FigmaQ8Tokens.tertiaryFixedDimLight,
    onTertiaryFixedVariant: FigmaQ8Tokens.onTertiaryFixedVariantLight,
    error: FigmaQ8Tokens.errorLight,
    onError: FigmaQ8Tokens.onErrorLight,
    errorContainer: FigmaQ8Tokens.errorContainerLight,
    onErrorContainer: FigmaQ8Tokens.onErrorContainerLight,
    outline: FigmaQ8Tokens.outlineLight,
    background: FigmaQ8Tokens.backgroundLight,
    onBackground: FigmaQ8Tokens.onBackgroundLight,
    surface: FigmaQ8Tokens.surfaceLight,
    onSurface: FigmaQ8Tokens.onSurfaceLight,
    surfaceVariant: FigmaQ8Tokens.surfaceVariantLight,
    onSurfaceVariant: FigmaQ8Tokens.onSurfaceVariantLight,
    inverseSurface: FigmaQ8Tokens.inverseSurfaceLight,
    inverseOnSurface: FigmaQ8Tokens.inverseOnSurfaceLight,
    inversePrimary: FigmaQ8Tokens.inversePrimaryLight,
    shadow: FigmaQ8Tokens.shadowLight,
    surfaceTint: FigmaQ8Tokens.surfaceTintLight,
    outlineVariant: FigmaQ8Tokens.outlineVariantLight,
    scrim: FigmaQ8Tokens.scrimLight,
    surfaceContainerHighest: FigmaQ8Tokens.surfaceContainerHighestLight,
    surfaceContainerHigh: FigmaQ8Tokens.surfaceContainerHighLight,
    surfaceContainer: FigmaQ8Tokens.surfaceContainerLight,
    surfaceContainerLow: FigmaQ8Tokens.surfaceContainerLowLight,
    surfaceContainerLowest: FigmaQ8Tokens.surfaceContainerLowestLight,
    surfaceBright: FigmaQ8Tokens.surfaceBrightLight,
    surfaceDim: FigmaQ8Tokens.surfaceDimLight,
  );

  /// Retrieve the nearest [FigmaQ8Color] from the widget tree.
  static FigmaQ8Color of(BuildContext context) {
    return Theme.of(context).extension<FigmaQ8Color>()!;
  }

  @override
  FigmaQ8Color copyWith({
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? primaryFixed,
    Color? onPrimaryFixed,
    Color? primaryFixedDim,
    Color? onPrimaryFixedVariant,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? secondaryFixed,
    Color? onSecondaryFixed,
    Color? secondaryFixedDim,
    Color? onSecondaryFixedVariant,
    Color? tertiary,
    Color? onTertiary,
    Color? tertiaryContainer,
    Color? onTertiaryContainer,
    Color? tertiaryFixed,
    Color? onTertiaryFixed,
    Color? tertiaryFixedDim,
    Color? onTertiaryFixedVariant,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? outline,
    Color? background,
    Color? onBackground,
    Color? surface,
    Color? onSurface,
    Color? surfaceVariant,
    Color? onSurfaceVariant,
    Color? inverseSurface,
    Color? inverseOnSurface,
    Color? inversePrimary,
    Color? shadow,
    Color? surfaceTint,
    Color? outlineVariant,
    Color? scrim,
    Color? surfaceContainerHighest,
    Color? surfaceContainerHigh,
    Color? surfaceContainer,
    Color? surfaceContainerLow,
    Color? surfaceContainerLowest,
    Color? surfaceBright,
    Color? surfaceDim,
  }) {
    return FigmaQ8Color(
      primary: primary ?? this.primary,
      onPrimary: onPrimary ?? this.onPrimary,
      primaryContainer: primaryContainer ?? this.primaryContainer,
      onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
      primaryFixed: primaryFixed ?? this.primaryFixed,
      onPrimaryFixed: onPrimaryFixed ?? this.onPrimaryFixed,
      primaryFixedDim: primaryFixedDim ?? this.primaryFixedDim,
      onPrimaryFixedVariant: onPrimaryFixedVariant ?? this.onPrimaryFixedVariant,
      secondary: secondary ?? this.secondary,
      onSecondary: onSecondary ?? this.onSecondary,
      secondaryContainer: secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
      secondaryFixed: secondaryFixed ?? this.secondaryFixed,
      onSecondaryFixed: onSecondaryFixed ?? this.onSecondaryFixed,
      secondaryFixedDim: secondaryFixedDim ?? this.secondaryFixedDim,
      onSecondaryFixedVariant: onSecondaryFixedVariant ?? this.onSecondaryFixedVariant,
      tertiary: tertiary ?? this.tertiary,
      onTertiary: onTertiary ?? this.onTertiary,
      tertiaryContainer: tertiaryContainer ?? this.tertiaryContainer,
      onTertiaryContainer: onTertiaryContainer ?? this.onTertiaryContainer,
      tertiaryFixed: tertiaryFixed ?? this.tertiaryFixed,
      onTertiaryFixed: onTertiaryFixed ?? this.onTertiaryFixed,
      tertiaryFixedDim: tertiaryFixedDim ?? this.tertiaryFixedDim,
      onTertiaryFixedVariant: onTertiaryFixedVariant ?? this.onTertiaryFixedVariant,
      error: error ?? this.error,
      onError: onError ?? this.onError,
      errorContainer: errorContainer ?? this.errorContainer,
      onErrorContainer: onErrorContainer ?? this.onErrorContainer,
      outline: outline ?? this.outline,
      background: background ?? this.background,
      onBackground: onBackground ?? this.onBackground,
      surface: surface ?? this.surface,
      onSurface: onSurface ?? this.onSurface,
      surfaceVariant: surfaceVariant ?? this.surfaceVariant,
      onSurfaceVariant: onSurfaceVariant ?? this.onSurfaceVariant,
      inverseSurface: inverseSurface ?? this.inverseSurface,
      inverseOnSurface: inverseOnSurface ?? this.inverseOnSurface,
      inversePrimary: inversePrimary ?? this.inversePrimary,
      shadow: shadow ?? this.shadow,
      surfaceTint: surfaceTint ?? this.surfaceTint,
      outlineVariant: outlineVariant ?? this.outlineVariant,
      scrim: scrim ?? this.scrim,
      surfaceContainerHighest: surfaceContainerHighest ?? this.surfaceContainerHighest,
      surfaceContainerHigh: surfaceContainerHigh ?? this.surfaceContainerHigh,
      surfaceContainer: surfaceContainer ?? this.surfaceContainer,
      surfaceContainerLow: surfaceContainerLow ?? this.surfaceContainerLow,
      surfaceContainerLowest: surfaceContainerLowest ?? this.surfaceContainerLowest,
      surfaceBright: surfaceBright ?? this.surfaceBright,
      surfaceDim: surfaceDim ?? this.surfaceDim,
    );
  }

  @override
  FigmaQ8Color lerp(covariant FigmaQ8Color? other, double t) {
    if (other == null) return this;
    return FigmaQ8Color(
      primary: Color.lerp(primary, other.primary, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      primaryContainer: Color.lerp(primaryContainer, other.primaryContainer, t)!,
      onPrimaryContainer: Color.lerp(onPrimaryContainer, other.onPrimaryContainer, t)!,
      primaryFixed: Color.lerp(primaryFixed, other.primaryFixed, t)!,
      onPrimaryFixed: Color.lerp(onPrimaryFixed, other.onPrimaryFixed, t)!,
      primaryFixedDim: Color.lerp(primaryFixedDim, other.primaryFixedDim, t)!,
      onPrimaryFixedVariant: Color.lerp(onPrimaryFixedVariant, other.onPrimaryFixedVariant, t)!,
      secondary: Color.lerp(secondary, other.secondary, t)!,
      onSecondary: Color.lerp(onSecondary, other.onSecondary, t)!,
      secondaryContainer: Color.lerp(secondaryContainer, other.secondaryContainer, t)!,
      onSecondaryContainer: Color.lerp(onSecondaryContainer, other.onSecondaryContainer, t)!,
      secondaryFixed: Color.lerp(secondaryFixed, other.secondaryFixed, t)!,
      onSecondaryFixed: Color.lerp(onSecondaryFixed, other.onSecondaryFixed, t)!,
      secondaryFixedDim: Color.lerp(secondaryFixedDim, other.secondaryFixedDim, t)!,
      onSecondaryFixedVariant:
          Color.lerp(onSecondaryFixedVariant, other.onSecondaryFixedVariant, t)!,
      tertiary: Color.lerp(tertiary, other.tertiary, t)!,
      onTertiary: Color.lerp(onTertiary, other.onTertiary, t)!,
      tertiaryContainer: Color.lerp(tertiaryContainer, other.tertiaryContainer, t)!,
      onTertiaryContainer: Color.lerp(onTertiaryContainer, other.onTertiaryContainer, t)!,
      tertiaryFixed: Color.lerp(tertiaryFixed, other.tertiaryFixed, t)!,
      onTertiaryFixed: Color.lerp(onTertiaryFixed, other.onTertiaryFixed, t)!,
      tertiaryFixedDim: Color.lerp(tertiaryFixedDim, other.tertiaryFixedDim, t)!,
      onTertiaryFixedVariant: Color.lerp(onTertiaryFixedVariant, other.onTertiaryFixedVariant, t)!,
      error: Color.lerp(error, other.error, t)!,
      onError: Color.lerp(onError, other.onError, t)!,
      errorContainer: Color.lerp(errorContainer, other.errorContainer, t)!,
      onErrorContainer: Color.lerp(onErrorContainer, other.onErrorContainer, t)!,
      outline: Color.lerp(outline, other.outline, t)!,
      background: Color.lerp(background, other.background, t)!,
      onBackground: Color.lerp(onBackground, other.onBackground, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      onSurface: Color.lerp(onSurface, other.onSurface, t)!,
      surfaceVariant: Color.lerp(surfaceVariant, other.surfaceVariant, t)!,
      onSurfaceVariant: Color.lerp(onSurfaceVariant, other.onSurfaceVariant, t)!,
      inverseSurface: Color.lerp(inverseSurface, other.inverseSurface, t)!,
      inverseOnSurface: Color.lerp(inverseOnSurface, other.inverseOnSurface, t)!,
      inversePrimary: Color.lerp(inversePrimary, other.inversePrimary, t)!,
      shadow: Color.lerp(shadow, other.shadow, t)!,
      surfaceTint: Color.lerp(surfaceTint, other.surfaceTint, t)!,
      outlineVariant: Color.lerp(outlineVariant, other.outlineVariant, t)!,
      scrim: Color.lerp(scrim, other.scrim, t)!,
      surfaceContainerHighest:
          Color.lerp(surfaceContainerHighest, other.surfaceContainerHighest, t)!,
      surfaceContainerHigh: Color.lerp(surfaceContainerHigh, other.surfaceContainerHigh, t)!,
      surfaceContainer: Color.lerp(surfaceContainer, other.surfaceContainer, t)!,
      surfaceContainerLow: Color.lerp(surfaceContainerLow, other.surfaceContainerLow, t)!,
      surfaceContainerLowest: Color.lerp(surfaceContainerLowest, other.surfaceContainerLowest, t)!,
      surfaceBright: Color.lerp(surfaceBright, other.surfaceBright, t)!,
      surfaceDim: Color.lerp(surfaceDim, other.surfaceDim, t)!,
    );
  }
}

class FigmaQ8Corners extends ThemeExtension<FigmaQ8Corners> {
  final double cornerNone;
  final double cornerExtraSmall;
  final double cornerSmall;
  final double cornerMedium;
  final double cornerLarge;
  final double cornerExtraLarge;
  final double cornerFull;
  final double cornerLargeIncreased;
  final double cornerExtraLargeIncreased;
  final double cornerExtraExtraLarge;

  const FigmaQ8Corners({
    required this.cornerNone,
    required this.cornerExtraSmall,
    required this.cornerSmall,
    required this.cornerMedium,
    required this.cornerLarge,
    required this.cornerExtraLarge,
    required this.cornerFull,
    required this.cornerLargeIncreased,
    required this.cornerExtraLargeIncreased,
    required this.cornerExtraExtraLarge,
  });

  static const corner = FigmaQ8Corners(
    cornerNone: FigmaQ8Tokens.cornerNoneCorner,
    cornerExtraSmall: FigmaQ8Tokens.cornerExtraSmallCorner,
    cornerSmall: FigmaQ8Tokens.cornerSmallCorner,
    cornerMedium: FigmaQ8Tokens.cornerMediumCorner,
    cornerLarge: FigmaQ8Tokens.cornerLargeCorner,
    cornerExtraLarge: FigmaQ8Tokens.cornerExtraLargeCorner,
    cornerFull: FigmaQ8Tokens.cornerFullCorner,
    cornerLargeIncreased: FigmaQ8Tokens.cornerLargeIncreasedCorner,
    cornerExtraLargeIncreased: FigmaQ8Tokens.cornerExtraLargeIncreasedCorner,
    cornerExtraExtraLarge: FigmaQ8Tokens.cornerExtraExtraLargeCorner,
  );

  /// Retrieve the nearest [FigmaQ8Corners] from the widget tree.
  static FigmaQ8Corners of(BuildContext context) {
    return Theme.of(context).extension<FigmaQ8Corners>()!;
  }

  @override
  FigmaQ8Corners copyWith({
    double? cornerNone,
    double? cornerExtraSmall,
    double? cornerSmall,
    double? cornerMedium,
    double? cornerLarge,
    double? cornerExtraLarge,
    double? cornerFull,
    double? cornerLargeIncreased,
    double? cornerExtraLargeIncreased,
    double? cornerExtraExtraLarge,
  }) {
    return FigmaQ8Corners(
      cornerNone: cornerNone ?? this.cornerNone,
      cornerExtraSmall: cornerExtraSmall ?? this.cornerExtraSmall,
      cornerSmall: cornerSmall ?? this.cornerSmall,
      cornerMedium: cornerMedium ?? this.cornerMedium,
      cornerLarge: cornerLarge ?? this.cornerLarge,
      cornerExtraLarge: cornerExtraLarge ?? this.cornerExtraLarge,
      cornerFull: cornerFull ?? this.cornerFull,
      cornerLargeIncreased: cornerLargeIncreased ?? this.cornerLargeIncreased,
      cornerExtraLargeIncreased: cornerExtraLargeIncreased ?? this.cornerExtraLargeIncreased,
      cornerExtraExtraLarge: cornerExtraExtraLarge ?? this.cornerExtraExtraLarge,
    );
  }

  @override
  FigmaQ8Corners lerp(covariant FigmaQ8Corners? other, double t) {
    if (other == null) return this;
    return FigmaQ8Corners(
      cornerNone: lerpDouble(cornerNone, other.cornerNone, t)!,
      cornerExtraSmall: lerpDouble(cornerExtraSmall, other.cornerExtraSmall, t)!,
      cornerSmall: lerpDouble(cornerSmall, other.cornerSmall, t)!,
      cornerMedium: lerpDouble(cornerMedium, other.cornerMedium, t)!,
      cornerLarge: lerpDouble(cornerLarge, other.cornerLarge, t)!,
      cornerExtraLarge: lerpDouble(cornerExtraLarge, other.cornerExtraLarge, t)!,
      cornerFull: lerpDouble(cornerFull, other.cornerFull, t)!,
      cornerLargeIncreased: lerpDouble(cornerLargeIncreased, other.cornerLargeIncreased, t)!,
      cornerExtraLargeIncreased:
          lerpDouble(cornerExtraLargeIncreased, other.cornerExtraLargeIncreased, t)!,
      cornerExtraExtraLarge: lerpDouble(cornerExtraExtraLarge, other.cornerExtraExtraLarge, t)!,
    );
  }
}

class FigmaQ8Spacings extends ThemeExtension<FigmaQ8Spacings> {
  final double space4;
  final double space8;
  final double space10;
  final double space12;
  final double space14;
  final double space16;
  final double space18;
  final double space20;
  final double space24;
  final double space30;
  final double space40;
  final double space60;
  final double space100;
  final double space120;
  final double spaceNone;

  const FigmaQ8Spacings({
    required this.space4,
    required this.space8,
    required this.space10,
    required this.space12,
    required this.space14,
    required this.space16,
    required this.space18,
    required this.space20,
    required this.space24,
    required this.space30,
    required this.space40,
    required this.space60,
    required this.space100,
    required this.space120,
    required this.spaceNone,
  });

  static const spacing = FigmaQ8Spacings(
    space4: FigmaQ8Tokens.space4Spacing,
    space8: FigmaQ8Tokens.space8Spacing,
    space10: FigmaQ8Tokens.space10Spacing,
    space12: FigmaQ8Tokens.space12Spacing,
    space14: FigmaQ8Tokens.space14Spacing,
    space16: FigmaQ8Tokens.space16Spacing,
    space18: FigmaQ8Tokens.space18Spacing,
    space20: FigmaQ8Tokens.space20Spacing,
    space24: FigmaQ8Tokens.space24Spacing,
    space30: FigmaQ8Tokens.space30Spacing,
    space40: FigmaQ8Tokens.space40Spacing,
    space60: FigmaQ8Tokens.space60Spacing,
    space100: FigmaQ8Tokens.space100Spacing,
    space120: FigmaQ8Tokens.space120Spacing,
    spaceNone: FigmaQ8Tokens.spaceNoneSpacing,
  );

  /// Retrieve the nearest [FigmaQ8Spacings] from the widget tree.
  static FigmaQ8Spacings of(BuildContext context) {
    return Theme.of(context).extension<FigmaQ8Spacings>()!;
  }

  @override
  FigmaQ8Spacings copyWith({
    double? space4,
    double? space8,
    double? space10,
    double? space12,
    double? space14,
    double? space16,
    double? space18,
    double? space20,
    double? space24,
    double? space30,
    double? space40,
    double? space60,
    double? space100,
    double? space120,
    double? spaceNone,
  }) {
    return FigmaQ8Spacings(
      space4: space4 ?? this.space4,
      space8: space8 ?? this.space8,
      space10: space10 ?? this.space10,
      space12: space12 ?? this.space12,
      space14: space14 ?? this.space14,
      space16: space16 ?? this.space16,
      space18: space18 ?? this.space18,
      space20: space20 ?? this.space20,
      space24: space24 ?? this.space24,
      space30: space30 ?? this.space30,
      space40: space40 ?? this.space40,
      space60: space60 ?? this.space60,
      space100: space100 ?? this.space100,
      space120: space120 ?? this.space120,
      spaceNone: spaceNone ?? this.spaceNone,
    );
  }

  @override
  FigmaQ8Spacings lerp(covariant FigmaQ8Spacings? other, double t) {
    if (other == null) return this;
    return FigmaQ8Spacings(
      space4: lerpDouble(space4, other.space4, t)!,
      space8: lerpDouble(space8, other.space8, t)!,
      space10: lerpDouble(space10, other.space10, t)!,
      space12: lerpDouble(space12, other.space12, t)!,
      space14: lerpDouble(space14, other.space14, t)!,
      space16: lerpDouble(space16, other.space16, t)!,
      space18: lerpDouble(space18, other.space18, t)!,
      space20: lerpDouble(space20, other.space20, t)!,
      space24: lerpDouble(space24, other.space24, t)!,
      space30: lerpDouble(space30, other.space30, t)!,
      space40: lerpDouble(space40, other.space40, t)!,
      space60: lerpDouble(space60, other.space60, t)!,
      space100: lerpDouble(space100, other.space100, t)!,
      space120: lerpDouble(space120, other.space120, t)!,
      spaceNone: lerpDouble(spaceNone, other.spaceNone, t)!,
    );
  }
}

class FigmaQ8Typography extends ThemeExtension<FigmaQ8Typography> {
  final TextStyle typeDisplayLarge;
  final TextStyle typeDisplayMedium;
  final TextStyle typeDisplaySmall;
  final TextStyle typeHeadlineLarge;
  final TextStyle typeHeadlineMedium;
  final TextStyle typeHeadlineSmall;
  final TextStyle typeTitleLarge;
  final TextStyle typeTitleMedium;
  final TextStyle typeTitleSmall;
  final TextStyle typeBodyLarge;
  final TextStyle typeBodyMedium;
  final TextStyle typeBodySmall;
  final TextStyle typeLabelLarge;
  final TextStyle typeLabelMedium;
  final TextStyle typeLabelSmall;

  const FigmaQ8Typography({
    required this.typeDisplayLarge,
    required this.typeDisplayMedium,
    required this.typeDisplaySmall,
    required this.typeHeadlineLarge,
    required this.typeHeadlineMedium,
    required this.typeHeadlineSmall,
    required this.typeTitleLarge,
    required this.typeTitleMedium,
    required this.typeTitleSmall,
    required this.typeBodyLarge,
    required this.typeBodyMedium,
    required this.typeBodySmall,
    required this.typeLabelLarge,
    required this.typeLabelMedium,
    required this.typeLabelSmall,
  });

  static const desktop = FigmaQ8Typography(
    typeDisplayLarge: FigmaQ8Tokens.typeDisplayLargeDesktop,
    typeDisplayMedium: FigmaQ8Tokens.typeDisplayMediumDesktop,
    typeDisplaySmall: FigmaQ8Tokens.typeDisplaySmallDesktop,
    typeHeadlineLarge: FigmaQ8Tokens.typeHeadlineLargeDesktop,
    typeHeadlineMedium: FigmaQ8Tokens.typeHeadlineMediumDesktop,
    typeHeadlineSmall: FigmaQ8Tokens.typeHeadlineSmallDesktop,
    typeTitleLarge: FigmaQ8Tokens.typeTitleLargeDesktop,
    typeTitleMedium: FigmaQ8Tokens.typeTitleMediumDesktop,
    typeTitleSmall: FigmaQ8Tokens.typeTitleSmallDesktop,
    typeBodyLarge: FigmaQ8Tokens.typeBodyLargeDesktop,
    typeBodyMedium: FigmaQ8Tokens.typeBodyMediumDesktop,
    typeBodySmall: FigmaQ8Tokens.typeBodySmallDesktop,
    typeLabelLarge: FigmaQ8Tokens.typeLabelLargeDesktop,
    typeLabelMedium: FigmaQ8Tokens.typeLabelMediumDesktop,
    typeLabelSmall: FigmaQ8Tokens.typeLabelSmallDesktop,
  );

  static const mobile = FigmaQ8Typography(
    typeDisplayLarge: FigmaQ8Tokens.typeDisplayLargeMobile,
    typeDisplayMedium: FigmaQ8Tokens.typeDisplayMediumMobile,
    typeDisplaySmall: FigmaQ8Tokens.typeDisplaySmallMobile,
    typeHeadlineLarge: FigmaQ8Tokens.typeHeadlineLargeMobile,
    typeHeadlineMedium: FigmaQ8Tokens.typeHeadlineMediumMobile,
    typeHeadlineSmall: FigmaQ8Tokens.typeHeadlineSmallMobile,
    typeTitleLarge: FigmaQ8Tokens.typeTitleLargeMobile,
    typeTitleMedium: FigmaQ8Tokens.typeTitleMediumMobile,
    typeTitleSmall: FigmaQ8Tokens.typeTitleSmallMobile,
    typeBodyLarge: FigmaQ8Tokens.typeBodyLargeMobile,
    typeBodyMedium: FigmaQ8Tokens.typeBodyMediumMobile,
    typeBodySmall: FigmaQ8Tokens.typeBodySmallMobile,
    typeLabelLarge: FigmaQ8Tokens.typeLabelLargeMobile,
    typeLabelMedium: FigmaQ8Tokens.typeLabelMediumMobile,
    typeLabelSmall: FigmaQ8Tokens.typeLabelSmallMobile,
  );

  static const tablet = FigmaQ8Typography(
    typeDisplayLarge: FigmaQ8Tokens.typeDisplayLargeTablet,
    typeDisplayMedium: FigmaQ8Tokens.typeDisplayMediumTablet,
    typeDisplaySmall: FigmaQ8Tokens.typeDisplaySmallTablet,
    typeHeadlineLarge: FigmaQ8Tokens.typeHeadlineLargeTablet,
    typeHeadlineMedium: FigmaQ8Tokens.typeHeadlineMediumTablet,
    typeHeadlineSmall: FigmaQ8Tokens.typeHeadlineSmallTablet,
    typeTitleLarge: FigmaQ8Tokens.typeTitleLargeTablet,
    typeTitleMedium: FigmaQ8Tokens.typeTitleMediumTablet,
    typeTitleSmall: FigmaQ8Tokens.typeTitleSmallTablet,
    typeBodyLarge: FigmaQ8Tokens.typeBodyLargeTablet,
    typeBodyMedium: FigmaQ8Tokens.typeBodyMediumTablet,
    typeBodySmall: FigmaQ8Tokens.typeBodySmallTablet,
    typeLabelLarge: FigmaQ8Tokens.typeLabelLargeTablet,
    typeLabelMedium: FigmaQ8Tokens.typeLabelMediumTablet,
    typeLabelSmall: FigmaQ8Tokens.typeLabelSmallTablet,
  );

  /// Retrieve the nearest [FigmaQ8Typography] from the widget tree.
  static FigmaQ8Typography of(BuildContext context) {
    return Theme.of(context).extension<FigmaQ8Typography>()!;
  }

  @override
  FigmaQ8Typography copyWith({
    TextStyle? typeDisplayLarge,
    TextStyle? typeDisplayMedium,
    TextStyle? typeDisplaySmall,
    TextStyle? typeHeadlineLarge,
    TextStyle? typeHeadlineMedium,
    TextStyle? typeHeadlineSmall,
    TextStyle? typeTitleLarge,
    TextStyle? typeTitleMedium,
    TextStyle? typeTitleSmall,
    TextStyle? typeBodyLarge,
    TextStyle? typeBodyMedium,
    TextStyle? typeBodySmall,
    TextStyle? typeLabelLarge,
    TextStyle? typeLabelMedium,
    TextStyle? typeLabelSmall,
  }) {
    return FigmaQ8Typography(
      typeDisplayLarge: typeDisplayLarge ?? this.typeDisplayLarge,
      typeDisplayMedium: typeDisplayMedium ?? this.typeDisplayMedium,
      typeDisplaySmall: typeDisplaySmall ?? this.typeDisplaySmall,
      typeHeadlineLarge: typeHeadlineLarge ?? this.typeHeadlineLarge,
      typeHeadlineMedium: typeHeadlineMedium ?? this.typeHeadlineMedium,
      typeHeadlineSmall: typeHeadlineSmall ?? this.typeHeadlineSmall,
      typeTitleLarge: typeTitleLarge ?? this.typeTitleLarge,
      typeTitleMedium: typeTitleMedium ?? this.typeTitleMedium,
      typeTitleSmall: typeTitleSmall ?? this.typeTitleSmall,
      typeBodyLarge: typeBodyLarge ?? this.typeBodyLarge,
      typeBodyMedium: typeBodyMedium ?? this.typeBodyMedium,
      typeBodySmall: typeBodySmall ?? this.typeBodySmall,
      typeLabelLarge: typeLabelLarge ?? this.typeLabelLarge,
      typeLabelMedium: typeLabelMedium ?? this.typeLabelMedium,
      typeLabelSmall: typeLabelSmall ?? this.typeLabelSmall,
    );
  }

  @override
  FigmaQ8Typography lerp(covariant FigmaQ8Typography? other, double t) {
    if (other == null) return this;
    return FigmaQ8Typography(
      typeDisplayLarge: TextStyle.lerp(typeDisplayLarge, other.typeDisplayLarge, t)!,
      typeDisplayMedium: TextStyle.lerp(typeDisplayMedium, other.typeDisplayMedium, t)!,
      typeDisplaySmall: TextStyle.lerp(typeDisplaySmall, other.typeDisplaySmall, t)!,
      typeHeadlineLarge: TextStyle.lerp(typeHeadlineLarge, other.typeHeadlineLarge, t)!,
      typeHeadlineMedium: TextStyle.lerp(typeHeadlineMedium, other.typeHeadlineMedium, t)!,
      typeHeadlineSmall: TextStyle.lerp(typeHeadlineSmall, other.typeHeadlineSmall, t)!,
      typeTitleLarge: TextStyle.lerp(typeTitleLarge, other.typeTitleLarge, t)!,
      typeTitleMedium: TextStyle.lerp(typeTitleMedium, other.typeTitleMedium, t)!,
      typeTitleSmall: TextStyle.lerp(typeTitleSmall, other.typeTitleSmall, t)!,
      typeBodyLarge: TextStyle.lerp(typeBodyLarge, other.typeBodyLarge, t)!,
      typeBodyMedium: TextStyle.lerp(typeBodyMedium, other.typeBodyMedium, t)!,
      typeBodySmall: TextStyle.lerp(typeBodySmall, other.typeBodySmall, t)!,
      typeLabelLarge: TextStyle.lerp(typeLabelLarge, other.typeLabelLarge, t)!,
      typeLabelMedium: TextStyle.lerp(typeLabelMedium, other.typeLabelMedium, t)!,
      typeLabelSmall: TextStyle.lerp(typeLabelSmall, other.typeLabelSmall, t)!,
    );
  }
}

class _FigmaQ8ColorAccessor {
  const _FigmaQ8ColorAccessor();

  FigmaQ8Color get dark => FigmaQ8Color.dark;
  FigmaQ8Color get light => FigmaQ8Color.light;

  /// Retrieve [FigmaQ8Color] from the nearest [Theme].
  FigmaQ8Color of(BuildContext context) => FigmaQ8Color.of(context);
}

class _FigmaQ8CornersAccessor {
  const _FigmaQ8CornersAccessor();

  FigmaQ8Corners get corner => FigmaQ8Corners.corner;

  /// Retrieve [FigmaQ8Corners] from the nearest [Theme].
  FigmaQ8Corners of(BuildContext context) => FigmaQ8Corners.of(context);
}

class _FigmaQ8SpacingsAccessor {
  const _FigmaQ8SpacingsAccessor();

  FigmaQ8Spacings get spacing => FigmaQ8Spacings.spacing;

  /// Retrieve [FigmaQ8Spacings] from the nearest [Theme].
  FigmaQ8Spacings of(BuildContext context) => FigmaQ8Spacings.of(context);
}

class _FigmaQ8TypographyAccessor {
  const _FigmaQ8TypographyAccessor();

  FigmaQ8Typography get desktop => FigmaQ8Typography.desktop;
  FigmaQ8Typography get mobile => FigmaQ8Typography.mobile;
  FigmaQ8Typography get tablet => FigmaQ8Typography.tablet;

  /// Retrieve [FigmaQ8Typography] from the nearest [Theme].
  FigmaQ8Typography of(BuildContext context) => FigmaQ8Typography.of(context);
}

/// Top-level accessor for all Figma token collections.
class FigmaQ8 {
  FigmaQ8._();

  static const color = _FigmaQ8ColorAccessor();
  static const corners = _FigmaQ8CornersAccessor();
  static const spacings = _FigmaQ8SpacingsAccessor();
  static const typography = _FigmaQ8TypographyAccessor();

  // --- Mode presets (all collections at once) ---

  static List<ThemeExtension> get corner => [FigmaQ8Corners.corner];
  static List<ThemeExtension> get dark => [FigmaQ8Color.dark];
  static List<ThemeExtension> get desktop => [FigmaQ8Typography.desktop];
  static List<ThemeExtension> get light => [FigmaQ8Color.light];
  static List<ThemeExtension> get mobile => [FigmaQ8Typography.mobile];
  static List<ThemeExtension> get spacing => [FigmaQ8Spacings.spacing];
  static List<ThemeExtension> get tablet => [FigmaQ8Typography.tablet];
}

abstract class FigmaQ8Tokens {
  static const Color primaryFixedDimLight = Color(0xFFB5C4FF);
  static const Color onPrimaryDark = Color(0xFF0B2469);
  static const Color primaryContainerDark = Color(0xFF0B2469);
  static const Color onPrimaryContainerDark = Color(0xFFDCE1FF);
  static const Color primaryFixedDark = Color(0xFFDCE1FF);
  static const Color onPrimaryFixedDark = Color(0xFF02174B);
  static const Color primaryFixedDimDark = Color(0xFFB5C4FF);
  static const Color onPrimaryFixedVariantDark = Color(0xFF344479);
  static const Color secondaryDark = Color(0xFFC0BEBE);
  static const Color onSecondaryDark = Color(0xFFF5F5F5);
  static const Color secondaryContainerDark = Color(0xFF004D62);
  static const Color onSecondaryContainerDark = Color(0xFFBAEAFF);
  static const Color secondaryFixedDark = Color(0xFFBAEAFF);
  static const Color onSecondaryFixedDark = Color(0xFF001F29);
  static const Color secondaryFixedDimDark = Color(0xFF89D0ED);
  static const Color onSecondaryFixedVariantDark = Color(0xFF004D62);
  static const Color tertiaryDark = Color(0xFFFBB907);
  static const Color onTertiaryDark = Color(0xFFFFFFFF);
  static const Color tertiaryContainerDark = Color(0xFF594400);
  static const Color onTertiaryContainerDark = Color(0xFFFFDF95);
  static const Color tertiaryFixedDark = Color(0xFFFFDF95);
  static const Color onTertiaryFixedDark = Color(0xFF251A00);
  static const Color tertiaryFixedDimDark = Color(0xFFE6C36C);
  static const Color onTertiaryFixedVariantDark = Color(0xFF594400);
  static const Color errorDark = Color(0xFFFFB4AB);
  static const Color onErrorDark = Color(0xFF690005);
  static const Color errorContainerDark = Color(0xFF93000A);
  static const Color onErrorContainerDark = Color(0xFFFFDAD6);
  static const Color outlineDark = Color(0xFF899294);
  static const Color backgroundDark = Color(0xFF121318);
  static const Color onBackgroundDark = Color(0xFFE3E1E9);
  static const Color surfaceDark = Color(0xFF0E1415);
  static const Color onSurfaceDark = Color(0xFFDEE3E5);
  static const Color surfaceVariantDark = Color(0xFF3F484A);
  static const Color onSurfaceVariantDark = Color(0xFFBFC8CA);
  static const Color inverseSurfaceDark = Color(0xFFDEE3E5);
  static const Color inverseOnSurfaceDark = Color(0xFF2B3133);
  static const Color inversePrimaryDark = Color(0xFF4C5C92);
  static const Color shadowDark = Color(0xFF000000);
  static const Color surfaceTintDark = Color(0xFFB5C4FF);
  static const Color outlineVariantDark = Color(0xFF3F484A);
  static const Color scrimDark = Color(0xFF000000);
  static const Color surfaceContainerHighestDark = Color(0xFF303637);
  static const Color surfaceContainerHighDark = Color(0xFF252B2C);
  static const Color surfaceContainerDark = Color(0xFF1B2122);
  static const Color surfaceContainerLowDark = Color(0xFF171D1E);
  static const Color surfaceContainerLowestDark = Color(0xFF090F10);
  static const Color surfaceBrightDark = Color(0xFF343A3B);
  static const Color surfaceDimDark = Color(0xFF0E1415);
  static const Color primaryLight = Color(0xFF20419A);
  static const Color onPrimaryLight = Color(0xFFFFFFFF);
  static const Color primaryContainerLight = Color(0xFFE9ECF5);
  static const Color onPrimaryContainerLight = Color(0xFF344479);
  static const Color primaryFixedLight = Color(0xFFDCE1FF);
  static const Color onPrimaryFixedLight = Color(0xFF02174B);
  static const Color primaryDark = Color(0xFFFFFFFF);
  static const Color onPrimaryFixedVariantLight = Color(0xFF344479);
  static const Color secondaryLight = Color(0xFF5D74B1);
  static const Color onSecondaryLight = Color(0xFFFFFFFF);
  static const Color secondaryContainerLight = Color(0xFFE9ECF5);
  static const Color onSecondaryContainerLight = Color(0xFF20419A);
  static const Color secondaryFixedLight = Color(0xFFBAEAFF);
  static const Color onSecondaryFixedLight = Color(0xFFBAEAFF);
  static const Color secondaryFixedDimLight = Color(0xFF89D0ED);
  static const Color onSecondaryFixedVariantLight = Color(0xFF004D62);
  static const Color tertiaryLight = Color(0xFFFBB907);
  static const Color onTertiaryLight = Color(0xFF20419A);
  static const Color tertiaryContainerLight = Color(0xFFFFDF95);
  static const Color onTertiaryContainerLight = Color(0xFF594400);
  static const Color tertiaryFixedLight = Color(0xFFFFDF95);
  static const Color onTertiaryFixedLight = Color(0xFF251A00);
  static const Color tertiaryFixedDimLight = Color(0xFFE6C36C);
  static const Color onTertiaryFixedVariantLight = Color(0xFF594400);
  static const Color errorLight = Color(0xFFBA1A1A);
  static const Color onErrorLight = Color(0xFFFFFFFF);
  static const Color errorContainerLight = Color(0xFFFFDAD6);
  static const Color onErrorContainerLight = Color(0xFF93000A);
  static const Color outlineLight = Color(0xFF20419A);
  static const Color backgroundLight = Color(0xFFFFFFFF);
  static const Color onBackgroundLight = Color(0xFF20419A);
  static const Color surfaceLight = Color(0xFFFFFFFF);
  static const Color onSurfaceLight = Color(0xFF1D1B20);
  static const Color surfaceVariantLight = Color(0xFFE9ECF5);
  static const Color onSurfaceVariantLight = Color(0xFF20419A);
  static const Color inverseSurfaceLight = Color(0xFF2B3133);
  static const Color inverseOnSurfaceLight = Color(0xFFECF2F3);
  static const Color inversePrimaryLight = Color(0xFFB5C4FF);
  static const Color shadowLight = Color(0xFF000000);
  static const Color surfaceTintLight = Color(0xFF4C5C92);
  static const Color outlineVariantLight = Color(0xFFBFC8CA);
  static const Color scrimLight = Color(0xFF000000);
  static const Color surfaceContainerHighestLight = Color(0xFFDEE3E5);
  static const Color surfaceContainerHighLight = Color(0xFFE3E9EA);
  static const Color surfaceContainerLight = Color(0xFFE9EFF0);
  static const Color surfaceContainerLowLight = Color(0xFFEFF5F6);
  static const Color surfaceContainerLowestLight = Color(0xFFFFFFFF);
  static const Color surfaceBrightLight = Color(0xFFF5F5F5);
  static const Color surfaceDimLight = Color(0xFFD5DBDC);
  static const TextStyle typeLabelMediumTablet = TextStyle(
    fontSize: 12.0,
    height: 1.33,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelLargeTablet = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodySmallTablet = TextStyle(
    fontSize: 12.0,
    height: 1.33,
    letterSpacing: 0.4,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodyMediumTablet = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.25,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodyLargeTablet = TextStyle(
    fontSize: 16.0,
    height: 1.50,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleSmallTablet = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleMediumTablet = TextStyle(
    fontSize: 16.0,
    height: 1.38,
    letterSpacing: 0.15,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleLargeTablet = TextStyle(
    fontSize: 22.0,
    height: 1.36,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineSmallTablet = TextStyle(
    fontSize: 28.0,
    height: 1.36,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineMediumTablet = TextStyle(
    fontSize: 35.0,
    height: 1.37,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineLargeTablet = TextStyle(
    fontSize: 40.0,
    height: 1.40,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplaySmallTablet = TextStyle(
    fontSize: 36.0,
    height: 1.22,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplayMediumTablet = TextStyle(
    fontSize: 45.0,
    height: 1.16,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelSmallTablet = TextStyle(
    fontSize: 11.0,
    height: 1.45,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplayLargeTablet = TextStyle(
    fontSize: 57.0,
    height: 1.12,
    letterSpacing: -0.25,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelSmallMobile = TextStyle(
    fontSize: 11.0,
    height: 1.45,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelMediumMobile = TextStyle(
    fontSize: 12.0,
    height: 1.33,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelLargeMobile = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodySmallMobile = TextStyle(
    fontSize: 12.0,
    height: 1.33,
    letterSpacing: 0.4,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodyMediumMobile = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.25,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodyLargeMobile = TextStyle(
    fontSize: 16.0,
    height: 1.50,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleSmallMobile = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleMediumMobile = TextStyle(
    fontSize: 16.0,
    height: 1.38,
    letterSpacing: 0.15,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleLargeMobile = TextStyle(
    fontSize: 16.0,
    height: 1.38,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineSmallMobile = TextStyle(
    fontSize: 22.0,
    height: 1.55,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplayLargeDesktop = TextStyle(
    fontSize: 57.0,
    height: 1.12,
    letterSpacing: -0.25,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplayMediumDesktop = TextStyle(
    fontSize: 45.0,
    height: 1.16,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplaySmallDesktop = TextStyle(
    fontSize: 36.0,
    height: 1.22,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineLargeDesktop = TextStyle(
    fontSize: 40.0,
    height: 1.40,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineMediumDesktop = TextStyle(
    fontSize: 35.0,
    height: 1.37,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineSmallDesktop = TextStyle(
    fontSize: 28.0,
    height: 1.36,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleLargeDesktop = TextStyle(
    fontSize: 22.0,
    height: 1.36,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleMediumDesktop = TextStyle(
    fontSize: 16.0,
    height: 1.38,
    letterSpacing: 0.15,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeTitleSmallDesktop = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodyLargeDesktop = TextStyle(
    fontSize: 16.0,
    height: 1.50,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodyMediumDesktop = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.25,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeBodySmallDesktop = TextStyle(
    fontSize: 12.0,
    height: 1.33,
    letterSpacing: 0.4,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelLargeDesktop = TextStyle(
    fontSize: 14.0,
    height: 1.43,
    letterSpacing: 0.1,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelMediumDesktop = TextStyle(
    fontSize: 12.0,
    height: 1.33,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeLabelSmallDesktop = TextStyle(
    fontSize: 11.0,
    height: 1.45,
    letterSpacing: 0.5,
    fontWeight: FontWeight.w500,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplayLargeMobile = TextStyle(
    fontSize: 57.0,
    height: 1.12,
    letterSpacing: -0.25,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineMediumMobile = TextStyle(
    fontSize: 28.0,
    height: 1.36,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplaySmallMobile = TextStyle(
    fontSize: 36.0,
    height: 1.22,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeHeadlineLargeMobile = TextStyle(
    fontSize: 36.0,
    height: 1.39,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const TextStyle typeDisplayMediumMobile = TextStyle(
    fontSize: 45.0,
    height: 1.16,
    letterSpacing: 0.0,
    fontWeight: FontWeight.w400,
    fontFamily: 'Manrope',
  );
  static const double spaceNoneSpacing = 0;
  static const double space120Spacing = 120;
  static const double space100Spacing = 100;
  static const double space60Spacing = 60;
  static const double space40Spacing = 40;
  static const double space30Spacing = 30;
  static const double space24Spacing = 24;
  static const double space20Spacing = 20;
  static const double space18Spacing = 18;
  static const double space16Spacing = 16;
  static const double space14Spacing = 14;
  static const double space10Spacing = 10;
  static const double space8Spacing = 8;
  static const double space4Spacing = 4;
  static const double cornerExtraExtraLargeCorner = 48;
  static const double cornerExtraLargeIncreasedCorner = 32;
  static const double cornerLargeIncreasedCorner = 20;
  static const double cornerFullCorner = 1000;
  static const double cornerExtraLargeCorner = 28;
  static const double cornerLargeCorner = 15;
  static const double cornerMediumCorner = 10;
  static const double cornerSmallCorner = 8;
  static const double cornerExtraSmallCorner = 4;
  static const double cornerNoneCorner = 0;
  static const double space12Spacing = 12;
}

// --- BuildContext extensions ---

extension FigmaQ8ColorContext on BuildContext {
  FigmaQ8Color get color => FigmaQ8Color.of(this);
}

extension FigmaQ8CornersContext on BuildContext {
  FigmaQ8Corners get corners => FigmaQ8Corners.of(this);
}

extension FigmaQ8SpacingsContext on BuildContext {
  FigmaQ8Spacings get spacings => FigmaQ8Spacings.of(this);
}

extension FigmaQ8TypographyContext on BuildContext {
  FigmaQ8Typography get typography => FigmaQ8Typography.of(this);
}
